### ISSUE TITLE
__get does not allow null returns, but the functions it calls to generate the return value do

### ISSUE THREAD

**Issue by PaulMcML** [billythekid/dvla-ves#2]
Basically, we don't always get all the info back from the DVLA. For example, getCo2Emissions may return null, and this is allowed by the getCo2Emissions function return type.  However this is not allowed by the __get() function return type.

Need to change the return type to 
    public function __get(string $property): null|bool|int|string

I'll fork and make a PR, but as the get functions are public anyway, it's safest to use those.

**Comment by billythekid** [comment]
fixed in #3 

many thanks!
